/*
 * Generating the panel to get the nodes from the user
*/

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.math.*;
import java.util.*;
import java.lang.Math;
import java.io.*;

/**
 *
 * @author emil
 */
public class GuiForTsp extends javax.swing.JFrame {
     
     int count = 0;
     ArrayList xList = new ArrayList();
     ArrayList yList = new ArrayList();

    /** Creates new form GuiForTsp */
    class MousePanelA extends JPanel implements MouseListener{
	public MousePanelA(){
	    super();
	    addMouseListener(this);
	}

	int x;
	int y;

	public void paintComponent(Graphics g) {
	    super.paintComponent(g);
	    /* Graphics2D g2d = (Graphics2D) g.create();
	    for(int i = 0; i < xList.size(); i ++)
	    g2d.fillRect((Integer)xList.get(i),(Integer) yList.get(i), 5, 5);*/
	    g2d.dispose();
	}

	public void mouseClicked(MouseEvent mouse){
	    count++;   
	    x = mouse.getX();
	    y = mouse.getY();
	    xList.add(new Integer(x));
	    yList.add(new Integer(y));
	    repaint();
	}
	
	public void mouseEntered(MouseEvent mouse){ }   
	public void mouseExited(MouseEvent mouse){ }
	public void mousePressed(MouseEvent mouse){ }
	public void mouseReleased(MouseEvent mouse){ }
    }
    
    JButton jButton1;
    MousePanelA jPanel1;
    
    public GuiForTsp() {
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
	
        jButton1 = new javax.swing.JButton();
        jPanel1 = new MousePanelA();
	
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 157, 164));


        jButton1.setText("Generate ");
	jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
	

        jPanel1.setBackground(new java.awt.Color(67, 152, 46));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
           
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        
    

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
        // TODO add your handling code here:
	double pow1 = 0;
	double pow2 = 0;
	double dist = 0;
	StringBuffer buffer = new StringBuffer(count*count + 1);
	StringBuffer xl = new StringBuffer(count);
	StringBuffer yl = new StringBuffer(count);

	buffer.append((int)count + " "); 
  	for( int i = 0; i < count; i++) {
	    int x =  (Integer)xList.get(i);
	    int y =  (Integer)yList.get(i);
	    for(int j = 0; j <count; j++) {
		int x1 =  (Integer)xList.get(j);
		int y1 =  (Integer)yList.get(j);
		pow1 = Math.pow((x - x1),2);
		pow2 = Math.pow((y - y1),2);
		dist = Math.sqrt(pow1+pow2);
		dist = (int)dist;
		buffer.append((int)dist + " ");
	    }
	}
	xl.append(count + " ");
	for( int i = 0; i < count; i++) {
	    int x = (Integer)xList.get(i);
	    int y = (Integer)yList.get(i);
	    xl.append(x + " ");
	    yl.append(y + " ");
	    System.out.println("x " + xl);
	    System.out.println("y " + yl);
	}

	
	
	try{
	    PrintWriter outputStream1 = new PrintWriter(new FileWriter("Input to hadoop.txt"));
	    PrintWriter outputStream2 = new PrintWriter(new FileWriter("xylist.txt"));
	    outputStream2.println(xl);
	    outputStream2.println(yl);
	    outputStream2.close();
	    outputStream1.println(buffer);
	    outputStream1.close();
	} catch (IOException e) {
	    System.out.println("file not been created Exception");
	}
	
    }		
	
   
	
	
	
	/**
    * @param args the command line arguments
    */
  public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiForTsp().setVisible(true);
            }
        });

  }
    
    
    
    // Variables declaration - do not modify                     
    
    // End of variables declaration                   
    
}
