/*
 * Generate the output shortest path 
 */

import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.math.*;
import java.util.*;
import java.lang.Math;
import java.io.*;

/**
 *
 * @author emil
 */
public class InputGui extends javax.swing.JFrame {
    ArrayList x = new ArrayList();
    ArrayList y = new ArrayList();
    ArrayList path = new ArrayList();
    int x1 = 0,y1 = 0;
    int x2 =0,y2 = 0;
    int n = 0;
    Scanner s ;
    
    /** Creates new form GuiForTsp */
      class MousePanelA extends JPanel implements MouseListener{
	public MousePanelA(){
	    super();
	}

	public void paintComponent(Graphics g) {
	    super.paintComponent(g);
	    calcFunction();
	  Graphics2D g2d = (Graphics2D) g.create();
	    for(int i = 0; i < x.size(); i ++)
		g2d.fillRect((Integer)x.get(i),(Integer) y.get(i), 5, 5);
	    g2d.dispose();
	    //System.out.print("path ");
	    int index;
	    x1 = (Integer)x.get((Integer)path.get(0));
	    y1 = (Integer)y.get((Integer)path.get(0));
	    for( int i = 0; i < x.size(); i++) {
		//index =(Integer)path.get(i);
		x2 = (Integer)x.get((Integer)path.get(i));
		y2 = (Integer)y.get((Integer)path.get(i));
		System.out.print("x " + x2);
		System.out.println(" y " + y2);
		g.drawLine(x1,y1,x2,y2);
		x1 = x2;
		y1 = y2;
		//System.out.print((Integer)path.get(i) + " ");
	    }
	    g.drawLine(x1,y1,(Integer)x.get((Integer)path.get(0)),(Integer)y.get((Integer)path.get(0)));
	    //g.drawLine(10,20,30,40);
	}
	  
	public void calcFunction() {
          try{
	    Scanner in = new Scanner(new File("xylist.txt"));
	    n = in.nextInt();
	    //System.out.println("count " + n); 
	    int i = 0;
	    while(in.hasNextInt()) {
		if(i < n){
		    x.add(new Integer(in.nextInt()));
		}
		else if( i == n) {
		    System.out.println();
		}
		else{
		    y.add(new Integer(in.nextInt()));
		}
		i++;
	    }
	    
	} catch(IOException e) {
	    System.out.println("file not found");
	}
	  System.out.println("x " + x);
	  System.out.println("y " + y);
    
	
	  try{
	      s = new Scanner(new File("output/part-00000"));
	      int pathlength = s.nextInt();
//	      System.out.println("path length" + pathlength);
	      int i = 0;
	      while ( i < n) {
		  path.add(new Integer(s.next()));
		  //System.out.print(s.next() + " ");
		  i++;
	      }
	  } catch( IOException e) {
	      System.out.println("resultant output path file not found");
	  }
	}
	  public void mouseClicked(MouseEvent mouse){ } 	
	  public void mouseEntered(MouseEvent mouse){ }   
	  public void mouseExited(MouseEvent mouse){ }
	  public void mousePressed(MouseEvent mouse){ }
	  public void mouseReleased(MouseEvent mouse){ }
	  public void start() {
//	      System.out.println("inside start");
	   repaint();
	  }
      }
    
    
    MousePanelA jPanel1;
    
    public InputGui() {
	
	initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {
	
	
        jPanel1 = new MousePanelA();
	
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 157, 164));


      
        jPanel1.setBackground(new java.awt.Color(67, 152, 46));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
             
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56))
                       // .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
	jPanel1.start();
    }// </editor-fold>                        
    

  
	
	
	/**
    * @param args the command line arguments
    */
  public static void main(String args[]) {


	
	
	
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputGui().setVisible(true);
            }
        });
  }      
}
